# Generated by Django 4.2 on 2023-04-06 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomComplet', models.CharField(max_length=30)),
                ('cnie', models.CharField(max_length=15)),
                ('etatFamilial', models.CharField(max_length=30)),
                ('tailleMenage', models.CharField(max_length=20)),
                ('habitat', models.CharField(max_length=200)),
                ('adresse', models.CharField(max_length=200)),
                ('tel', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Enfant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=20)),
                ('age', models.IntegerField(default=0)),
                ('etablissement', models.CharField(max_length=40)),
                ('nScol', models.CharField(max_length=40)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goodApp.parent')),
            ],
        ),
    ]
