# Generated by Django 4.2 on 2023-04-06 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goodApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enfant',
            name='genre',
            field=models.CharField(choices=[('g', 'garçon'), ('f', 'fille')], max_length=20),
        ),
        migrations.AlterField(
            model_name='enfant',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enfants', to='goodApp.parent'),
        ),
    ]
