# Generated by Django 4.2 on 2023-04-06 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goodApp', '0003_myparentadmin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyParentAdmin',
        ),
    ]
